# Generated by Django 5.0.3 on 2024-03-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_address', models.TextField()),
                ('username', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('psw', models.TextField()),
                ('uniqueid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='recuiter_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('psw', models.TextField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
