# Generated by Django 4.1 on 2024-03-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylogin',
            name='reg_date',
            field=models.DateField(default='2024-03-11'),
            preserve_default=False,
        ),
    ]
