# Generated by Django 4.1 on 2024-03-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylogin',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recruiter_login',
            name='dob',
            field=models.DateField(),
        ),
    ]
