# Generated by Django 5.0.3 on 2024-03-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_uniqueids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_login',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
