# Generated by Django 5.0.3 on 2024-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0004_company_login_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('unique_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='company_login',
        ),
        migrations.DeleteModel(
            name='Company_login_v2',
        ),
    ]
