# Generated by Django 4.1 on 2024-03-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0005_companylogin_delete_company_login_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recuiter_login',
            new_name='recruiter_login',
        ),
    ]
