# Generated by Django 4.1 on 2024-03-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0007_gmail_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='posted_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('mail', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('skills', models.TextField()),
                ('work_loc', models.CharField(max_length=30)),
                ('hire_locs', models.CharField(max_length=30)),
                ('exp', models.CharField(max_length=10)),
                ('sallary', models.CharField(max_length=20)),
                ('job_des', models.TextField()),
                ('shift_time', models.CharField(max_length=10)),
                ('contact_no', models.CharField(max_length=20)),
                ('contact_mail', models.CharField(max_length=20)),
                ('job_address', models.TextField()),
                ('company_name', models.CharField(max_length=30)),
                ('recruiter_name', models.CharField(max_length=30)),
                ('uniqueid', models.CharField(max_length=20)),
            ],
        ),
    ]
