# Generated by Django 4.1 on 2024-03-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0008_posted_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='posted_jobs',
            name='uniquejobid',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
