# Generated by Django 4.1 on 2024-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0009_posted_jobs_uniquejobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmail_cv',
            name='contact_mail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gmail_cv',
            name='mail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='mail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recruiter_login',
            name='mail',
            field=models.TextField(),
        ),
    ]
